<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exceptions\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <None Remove="Exceptions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MediatR.Contracts" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HBlog.Domain\HBlog.Domain.csproj" />
    <ProjectReference Include="..\HBlog.Contract\HBlog.Contract.csproj" />
  </ItemGroup>

</Project>
