<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <None Remove="Components\UI\ConfirmationModal.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\UI\ConfirmationModal.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" />
    <PackageReference Include="Blazored.Toast" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HBlog.Domain\HBlog.Domain.csproj" />
    <ProjectReference Include="..\HBlog.Contract\HBlog.Contract.csproj" />
  </ItemGroup>

</Project>
