name: Deploy HBlog API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: 'hblog-web-api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/HBlog.Api


      - name: Build
        run: dotnet build --no-restore src/HBlog.Api

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: src/HBlog.Api


      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: hblog-web-api
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true